version: '3.7'

services:
  node:
    build: .
    container_name: ovh-availability-checker
    volumes:
      - logs:/app/logs
      - ./servers.json:/app/servers.json
    env_file: .env

volumes:
  logs:
